using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading;
using System.Transactions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Til.Lombok;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Til.Unity.Lombok {
    [Generator]
    public sealed class BufferSerialization : IIncrementalGenerator {
        private static readonly string AttributeName = typeof(ILombokAttribute).FullName!;

        public void Initialize(IncrementalGeneratorInitializationContext context) {
            var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeName,
                IsCandidate,
                Transform
            );
            context.AddSources(
                sources
            );
        }

        private bool IsCandidate(
            SyntaxNode node,
            CancellationToken cancellationToken) => node is ClassDeclarationSyntax;

        private GeneratorResult Transform(
            GeneratorAttributeSyntaxContext context,
            CancellationToken cancellationToken) {
            ClassDeclarationSyntax contextTargetNode = (ClassDeclarationSyntax)context.TargetNode;

            SemanticModel semanticModel = context.SemanticModel;

            if (!contextTargetNode.TryValidateType(
                    out var @namespace,
                    out var diagnostic
                )) {
                return new GeneratorResult(
                    diagnostic
                );
            }

            List<CSharpSyntaxNode> fieldList = new List<CSharpSyntaxNode>();

            foreach (var member in contextTargetNode.Members) {
                switch (member) {
                    // 检查成员是否是字段或属性  
                    case FieldDeclarationSyntax fieldDeclaration: {
                        AttributeSyntax? tryGetSpecifiedAttribute = fieldDeclaration.AttributeLists.tryGetSpecifiedAttribute(
                            nameof(BufferFieldAttribute)
                        );
                        if (tryGetSpecifiedAttribute is not null) {
                            foreach (VariableDeclaratorSyntax variableDeclaratorSyntax in fieldDeclaration.Declaration.Variables) {
                                fieldList.Add(
                                    variableDeclaratorSyntax
                                );
                            }
                        }
                        break;
                    }
                    case PropertyDeclarationSyntax propertyDeclaration: {
                        AttributeSyntax? tryGetSpecifiedAttribute = propertyDeclaration.AttributeLists.tryGetSpecifiedAttribute(
                            nameof(BufferFieldAttribute)
                        );
                        if (tryGetSpecifiedAttribute is not null) {
                            fieldList.Add(
                                tryGetSpecifiedAttribute
                            );
                        }
                        break;
                    }
                }
            }

            if (fieldList.Count == 0) {
                return GeneratorResult.Empty;
            }

            List<StatementSyntax> readFieldStatement = new List<StatementSyntax>();
            List<StatementSyntax> readDeltaFieldStatement = new List<StatementSyntax>();

            List<StatementSyntax> writeFieldStatement = new List<StatementSyntax>();
            List<StatementSyntax> writeDeltaFieldStatement = new List<StatementSyntax>();

            List<StatementSyntax> duplicateValueFieldStatement = new List<StatementSyntax>();

            bool isValueType = (semanticModel.GetSymbolInfo(
                                       contextTargetNode
                                   )
                                   .Symbol as ITypeSymbol)?.IsValueType
                               ?? false;

            if (!isValueType) {
                readFieldStatement.Add(
                    LocalDeclarationStatement(
                        VariableDeclaration(
                            ParseTypeName(
                                "bool"
                            ),
                            SeparatedList(
                                new[] {
                                    VariableDeclarator(
                                        "isNull"
                                    )
                                }
                            )
                        )
                    )
                );
                readFieldStatement.Add(
                    ExpressionStatement(
                        InvocationExpression(
                            IdentifierName(
                                "Unity.Netcode.ByteUnpacker.ReadValueBitPacked"
                            ),
                            ArgumentList(
                                SeparatedList(
                                    new[] {
                                        Argument(
                                            IdentifierName(
                                                "reader"
                                            )
                                        ),
                                        Argument(
                                                IdentifierName(
                                                    "isNull"
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.OutKeyword
                                                )
                                            )
                                    }
                                )
                            )
                        )
                    )
                );

                readFieldStatement.Add(
                    IfStatement(
                        IdentifierName(
                            "isNull"
                        ),
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName(
                                        "value"
                                    ),
                                    LiteralExpression(
                                        SyntaxKind.NullLiteralExpression
                                    )
                                )
                            ),
                            ReturnStatement(
                            )
                        )
                    )
                );

                readFieldStatement.Add(
                    ExpressionStatement(
                        AssignmentExpression(
                            SyntaxKind.SimpleAssignmentExpression,
                            IdentifierName(
                                "value"
                            ),
                            ObjectCreationExpression(
                                    ParseTypeName(
                                        contextTargetNode.Identifier.Text
                                    )
                                )
                                .WithArgumentList(
                                    ArgumentList()
                                )
                        )
                    )
                    /*IfStatement(
                        BinaryExpression(
                            SyntaxKind.EqualsExpression,
                            IdentifierName(
                                "value"
                            ),
                            LiteralExpression(
                                SyntaxKind.NullLiteralExpression
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName(
                                        "value"
                                    ),
                                    ObjectCreationExpression(
                                            ParseTypeName(
                                                contextTargetNode.Identifier.Text
                                            )
                                        )
                                        .WithArgumentList(
                                            ArgumentList()
                                        )
                                )
                            )
                        )
                    )*/
                );

                readDeltaFieldStatement.Add(
                    LocalDeclarationStatement(
                        VariableDeclaration(
                            ParseTypeName(
                                "bool"
                            ),
                            SeparatedList(
                                new[] {
                                    VariableDeclarator(
                                        "isNull"
                                    )
                                }
                            )
                        )
                    )
                );
                readDeltaFieldStatement.Add(
                    ExpressionStatement(
                        InvocationExpression(
                            IdentifierName(
                                "Unity.Netcode.ByteUnpacker.ReadValueBitPacked"
                            ),
                            ArgumentList(
                                SeparatedList(
                                    new[] {
                                        Argument(
                                            IdentifierName(
                                                "reader"
                                            )
                                        ),
                                        Argument(
                                                IdentifierName(
                                                    "isNull"
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.OutKeyword
                                                )
                                            )
                                    }
                                )
                            )
                        )
                    )
                );

                readDeltaFieldStatement.Add(
                    IfStatement(
                        IdentifierName(
                            "isNull"
                        ),
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName(
                                        "value"
                                    ),
                                    LiteralExpression(
                                        SyntaxKind.NullLiteralExpression
                                    )
                                )
                            ),
                            ReturnStatement(
                            )
                        )
                    )
                );

                readDeltaFieldStatement.Add(
                    IfStatement(
                        BinaryExpression(
                            SyntaxKind.EqualsExpression,
                            IdentifierName(
                                "value"
                            ),
                            LiteralExpression(
                                SyntaxKind.NullLiteralExpression
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName(
                                        "value"
                                    ),
                                    ObjectCreationExpression(
                                            ParseTypeName(
                                                contextTargetNode.Identifier.Text
                                            )
                                        )
                                        .WithArgumentList(
                                            ArgumentList()
                                        )
                                )
                            )
                        )
                    )
                );

                writeFieldStatement.Add(
                    IfStatement(
                        BinaryExpression(
                            SyntaxKind.EqualsExpression,
                            IdentifierName(
                                "value"
                            ),
                            LiteralExpression(
                                SyntaxKind.NullLiteralExpression
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                InvocationExpression(
                                    IdentifierName(
                                        "Unity.Netcode.BytePacker.WriteValuePacked"
                                    ),
                                    ArgumentList(
                                        SeparatedList(
                                            new[] {
                                                Argument(
                                                    IdentifierName(
                                                        "reader"
                                                    )
                                                ),
                                                Argument(
                                                    IdentifierName(
                                                        "true"
                                                    )
                                                ),
                                            }
                                        )
                                    )
                                )
                            ),
                            ReturnStatement()
                        )
                    )
                );

                writeDeltaFieldStatement.Add(
                    IfStatement(
                        BinaryExpression(
                            SyntaxKind.EqualsExpression,
                            IdentifierName(
                                "value"
                            ),
                            LiteralExpression(
                                SyntaxKind.NullLiteralExpression
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                InvocationExpression(
                                    IdentifierName(
                                        "Unity.Netcode.BytePacker.WriteValuePacked"
                                    ),
                                    ArgumentList(
                                        SeparatedList(
                                            new[] {
                                                Argument(
                                                    IdentifierName(
                                                        "reader"
                                                    )
                                                ),
                                                Argument(
                                                    IdentifierName(
                                                        "true"
                                                    )
                                                ),
                                            }
                                        )
                                    )
                                )
                            ),
                            ReturnStatement()
                        )
                    )
                );

                duplicateValueFieldStatement.Add(
                    IfStatement(
                        BinaryExpression(
                            SyntaxKind.EqualsExpression,
                            IdentifierName(
                                "value"
                            ),
                            LiteralExpression(
                                SyntaxKind.NullLiteralExpression
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName(
                                        "duplicatedValue"
                                    ),
                                    IdentifierName(
                                        "null"
                                    )
                                )
                            ),
                            ReturnStatement()
                        )
                    )
                );

                duplicateValueFieldStatement.Add(
                    IfStatement(
                        BinaryExpression(
                            SyntaxKind.EqualsExpression,
                            IdentifierName(
                                "duplicatedValue"
                            ),
                            LiteralExpression(
                                SyntaxKind.NullLiteralExpression
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName(
                                        "duplicatedValue"
                                    ),
                                    ObjectCreationExpression(
                                            ParseTypeName(
                                                contextTargetNode.Identifier.Text
                                            )
                                        )
                                        .WithArgumentList(
                                            ArgumentList()
                                        )
                                )
                            )
                        )
                    )
                );
            }

            foreach (CSharpSyntaxNode cSharpSyntaxNode in fieldList) {
                string type = cSharpSyntaxNode is VariableDeclaratorSyntax variableDeclaratorSyntax
                    ? ((VariableDeclarationSyntax)variableDeclaratorSyntax.Parent!).Type.ToString()
                    : ((PropertyDeclarationSyntax)cSharpSyntaxNode).Type.ToString();

                readFieldStatement.Add(
                    ExpressionStatement(
                        InvocationExpression(
                            MemberAccessExpression(
                                SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName(
                                    $"Unity.Netcode.NetworkVariableSerialization<{type}>"
                                ),
                                IdentifierName(
                                    "Read"
                                )
                            ),
                            ArgumentList(
                                SeparatedList(
                                    new List<ArgumentSyntax>() {
                                        Argument(
                                            IdentifierName(
                                                "reader"
                                            )
                                        ),
                                        Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "value"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.RefKeyword
                                                )
                                            )
                                    }
                                )
                            )
                        )
                    )
                );

                readDeltaFieldStatement.Add(
                    ExpressionStatement(
                        InvocationExpression(
                            MemberAccessExpression(
                                SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName(
                                    $"Unity.Netcode.NetworkVariableSerialization<{type}>"
                                ),
                                IdentifierName(
                                    "ReadDelta"
                                )
                            ),
                            ArgumentList(
                                SeparatedList(
                                    new List<ArgumentSyntax>() {
                                        Argument(
                                            IdentifierName(
                                                "reader"
                                            )
                                        ),
                                        Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "value"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.RefKeyword
                                                )
                                            )
                                    }
                                )
                            )
                        )
                    )
                );

                writeFieldStatement.Add(
                    ExpressionStatement(
                        InvocationExpression(
                            MemberAccessExpression(
                                SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName(
                                    $"Unity.Netcode.NetworkVariableSerialization<{type}>"
                                ),
                                IdentifierName(
                                    "Write"
                                )
                            ),
                            ArgumentList(
                                SeparatedList(
                                    new List<ArgumentSyntax>() {
                                        Argument(
                                            IdentifierName(
                                                "writer"
                                            )
                                        ),
                                        Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "value"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.RefKeyword
                                                )
                                            )
                                    }
                                )
                            )
                        )
                    )
                );

                writeDeltaFieldStatement.Add(
                    ExpressionStatement(
                        InvocationExpression(
                            IdentifierName(
                                $"Unity.Netcode.NetworkVariableSerialization<{type}>.WriteDelta"
                            ),
                            ArgumentList(
                                SeparatedList(
                                    new List<ArgumentSyntax>() {
                                        Argument(
                                            IdentifierName(
                                                "writer"
                                            )
                                        ),
                                        Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "value"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.RefKeyword
                                                )
                                            ),
                                        Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "previousValue"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            )
                                            .WithRefKindKeyword(
                                                Token(
                                                    SyntaxKind.RefKeyword
                                                )
                                            )
                                    }
                                )
                            )
                        )
                    )
                );

                duplicateValueFieldStatement.Add(
                    IfStatement(
                        PrefixUnaryExpression(
                            SyntaxKind.LogicalNotExpression,
                            InvocationExpression(
                                IdentifierName(
                                    "object.Equals"
                                ),
                                ArgumentList(
                                    SeparatedList(
                                        new[] {
                                            Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "duplicatedValue"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            ),
                                            Argument(
                                                MemberAccessExpression(
                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                    IdentifierName(
                                                        "value"
                                                    ),
                                                    IdentifierName(
                                                        cSharpSyntaxNode.ToString()
                                                    )
                                                )
                                            )
                                        }
                                    )
                                )
                            )
                        ),
                        Block(
                            ExpressionStatement(
                                InvocationExpression(
                                    IdentifierName(
                                        $"Unity.Netcode.NetworkVariableSerialization<{type}>.Duplicate"
                                    ),
                                    ArgumentList(
                                        SeparatedList(
                                            new List<ArgumentSyntax>() {
                                                Argument(
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            IdentifierName(
                                                                "value"
                                                            ),
                                                            IdentifierName(
                                                                cSharpSyntaxNode.ToString()
                                                            )
                                                        )
                                                    ),
                                                Argument(
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            IdentifierName(
                                                                "duplicatedValue"
                                                            ),
                                                            IdentifierName(
                                                                cSharpSyntaxNode.ToString()
                                                            )
                                                        )
                                                    )
                                                    .WithRefKindKeyword(
                                                        Token(
                                                            SyntaxKind.RefKeyword
                                                        )
                                                    )
                                            }
                                        )
                                    )
                                )
                            )
                        )
                    )
                );
            }

            MethodDeclarationSyntax readField = MethodDeclaration(
                    IdentifierName(
                        "void"
                    ),
                    "read"
                )
                .AddModifiers(
                    Token(
                        SyntaxKind.PublicKeyword
                    ),
                    Token(
                        SyntaxKind.StaticKeyword
                    )
                )
                .AddParameterListParameters(
                    Parameter(
                            Identifier(
                                "reader"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                "Unity.Netcode.FastBufferReader"
                            )
                        ),
                    Parameter(
                            Identifier(
                                "value"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.OutKeyword
                                )
                            )
                        )
                )
                .WithBody(
                    Block(
                        readFieldStatement
                    )
                );

            MethodDeclarationSyntax readDeltaField = MethodDeclaration(
                    IdentifierName(
                        "void"
                    ),
                    "readDelta"
                )
                .AddModifiers(
                    Token(
                        SyntaxKind.PublicKeyword
                    ),
                    Token(
                        SyntaxKind.StaticKeyword
                    )
                )
                .AddParameterListParameters(
                    Parameter(
                            Identifier(
                                "readDelta"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                "Unity.Netcode.FastBufferReader"
                            )
                        ),
                    Parameter(
                            Identifier(
                                "value"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.RefKeyword
                                )
                            )
                        )
                )
                .WithBody(
                    Block(
                        readDeltaFieldStatement
                    )
                );

            MethodDeclarationSyntax writeField = MethodDeclaration(
                    IdentifierName(
                        "void"
                    ),
                    "write"
                )
                .AddModifiers(
                    Token(
                        SyntaxKind.PublicKeyword
                    ),
                    Token(
                        SyntaxKind.StaticKeyword
                    )
                )
                .AddParameterListParameters(
                    Parameter(
                            Identifier(
                                "writer"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                "Unity.Netcode.FastBufferReader"
                            )
                        ),
                    Parameter(
                            Identifier(
                                "value"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.InKeyword
                                )
                            )
                        )
                )
                .WithBody(
                    Block(
                        writeFieldStatement
                    )
                );

            MethodDeclarationSyntax writeDeltaField = MethodDeclaration(
                    IdentifierName(
                        "void"
                    ),
                    "writeDelta"
                )
                .AddModifiers(
                    Token(
                        SyntaxKind.PublicKeyword
                    ),
                    Token(
                        SyntaxKind.StaticKeyword
                    )
                )
                .AddParameterListParameters(
                    Parameter(
                            Identifier(
                                "writer"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                "Unity.Netcode.FastBufferReader"
                            )
                        ),
                    Parameter(
                            Identifier(
                                "value"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.InKeyword
                                )
                            )
                        ),
                    Parameter(
                            Identifier(
                                "previousValue"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.InKeyword
                                )
                            )
                        )
                )
                .WithBody(
                    Block(
                        writeDeltaFieldStatement
                    )
                );

            MethodDeclarationSyntax duplicateValue = MethodDeclaration(
                    IdentifierName(
                        "void"
                    ),
                    "duplicateValue"
                )
                .AddModifiers(
                    Token(
                        SyntaxKind.PublicKeyword
                    ),
                    Token(
                        SyntaxKind.StaticKeyword
                    )
                )
                .AddParameterListParameters(
                    Parameter(
                            Identifier(
                                "value"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.InKeyword
                                )
                            )
                        ),
                    Parameter(
                            Identifier(
                                "duplicatedValue"
                            )
                        )
                        .WithType(
                            IdentifierName(
                                contextTargetNode.Identifier.Text
                            )
                        )
                        .WithModifiers(
                            TokenList(
                                Token(
                                    SyntaxKind.RefKeyword
                                )
                            )
                        )
                )
                .WithBody(
                    Block(
                        duplicateValueFieldStatement
                    )
                );

            return new GeneratorResult(
                contextTargetNode.GetHintName(
                    @namespace
                ),
                SourceText.From(
                    CompilationUnit()
                        .WithUsings(
                            contextTargetNode.GetUsings()
                        )
                        .AddMembers(
                            NamespaceDeclaration(
                                    @namespace
                                )
                                .AddMembers(
                                    contextTargetNode
                                        .CreateNewPartialClass()
                                        .WithMembers(
                                            List(
                                                new MemberDeclarationSyntax[] {
                                                    readField,
                                                    readDeltaField,
                                                    writeField,
                                                    writeDeltaField,
                                                    duplicateValue
                                                }
                                            )
                                        )
                                        /*.AddMembers(
                                            ClassDeclaration(
                                                    contextTargetNode.Identifier.Text + "Serializer"
                                                )
                                                .AddBaseListTypes(
                                                    SimpleBaseType(
                                                        ParseName(
                                                            $"INetworkVariableSerializer<{contextTargetNode.Identifier.Text}>"
                                                        )
                                                    )
                                                )
                                                .AddModifiers(
                                                    Token(
                                                        SyntaxKind.PublicKeyword
                                                    )
                                                )
                                                .AddMembers(
                                                    MethodDeclaration(
                                                        IdentifierName(
                                                            "void"
                                                        ),
                                                        "writeDelta"
                                                    ),
                                                    MethodDeclaration(
                                                        IdentifierName(
                                                            "void"
                                                        ),
                                                        "writeDelta"
                                                    ),
                                                    MethodDeclaration(
                                                        IdentifierName(
                                                            "void"
                                                        ),
                                                        "writeDelta"
                                                    ),
                                                    MethodDeclaration(
                                                        IdentifierName(
                                                            "void"
                                                        ),
                                                        "writeDelta"
                                                    ),
                                                    MethodDeclaration(
                                                        IdentifierName(
                                                            "void"
                                                        ),
                                                        "writeDelta"
                                                    ),
                                                    MethodDeclaration(
                                                        IdentifierName(
                                                            "void"
                                                        ),
                                                        "writeDelta"
                                                    )
                                                )
                                        )*/
                                        .AddMembers(
                                            ClassDeclaration(
                                                    contextTargetNode.Identifier.Text + "InitializeOnLoad"
                                                )
                                                .AddModifiers(
                                                    Token(
                                                        SyntaxKind.PublicKeyword
                                                    ),
                                                    Token(
                                                        SyntaxKind.StaticKeyword
                                                    )
                                                )
                                                .AddAttributeLists(
                                                    AttributeList(
                                                        SeparatedList(
                                                            new[] {
                                                                Attribute(
                                                                    ParseName(
                                                                        "UnityEditor.InitializeOnLoadAttribute"
                                                                    )
                                                                )
                                                            }
                                                        )
                                                    )
                                                )
                                                .AddMembers(
                                                    ConstructorDeclaration(
                                                            contextTargetNode.Identifier.Text + "InitializeOnLoad"
                                                        )
                                                        .AddModifiers(
                                                            Token(
                                                                SyntaxKind.StaticKeyword
                                                            )
                                                        )
                                                        .WithBody(
                                                            Block(
                                                                ExpressionStatement(
                                                                    AssignmentExpression(
                                                                        SyntaxKind.SimpleAssignmentExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            ParseTypeName(
                                                                                $"Unity.Netcode.UserNetworkVariableSerialization<{contextTargetNode.Identifier.Text}>"
                                                                            ),
                                                                            IdentifierName(
                                                                                "ReadValue"
                                                                            )
                                                                        ),
                                                                        IdentifierName(
                                                                            "read"
                                                                        )
                                                                    )
                                                                ),
                                                                ExpressionStatement(
                                                                    AssignmentExpression(
                                                                        SyntaxKind.SimpleAssignmentExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            ParseTypeName(
                                                                                $"Unity.Netcode.UserNetworkVariableSerialization<{contextTargetNode.Identifier.Text}>"
                                                                            ),
                                                                            IdentifierName(
                                                                                "WriteValue"
                                                                            )
                                                                        ),
                                                                        IdentifierName(
                                                                            "write"
                                                                        )
                                                                    )
                                                                ),
                                                                ExpressionStatement(
                                                                    AssignmentExpression(
                                                                        SyntaxKind.SimpleAssignmentExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            ParseTypeName(
                                                                                $"Unity.Netcode.UserNetworkVariableSerialization<{contextTargetNode.Identifier.Text}>"
                                                                            ),
                                                                            IdentifierName(
                                                                                "WriteDelta"
                                                                            )
                                                                        ),
                                                                        IdentifierName(
                                                                            "writeDelta"
                                                                        )
                                                                    )
                                                                ),
                                                                ExpressionStatement(
                                                                    AssignmentExpression(
                                                                        SyntaxKind.SimpleAssignmentExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            ParseTypeName(
                                                                                $"Unity.Netcode.UserNetworkVariableSerialization<{contextTargetNode.Identifier.Text}>"
                                                                            ),
                                                                            IdentifierName(
                                                                                "ReadDelta"
                                                                            )
                                                                        ),
                                                                        IdentifierName(
                                                                            "readDelta"
                                                                        )
                                                                    )
                                                                ),
                                                                ExpressionStatement(
                                                                    AssignmentExpression(
                                                                        SyntaxKind.SimpleAssignmentExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            ParseTypeName(
                                                                                $"Unity.Netcode.UserNetworkVariableSerialization<{contextTargetNode.Identifier.Text}>"
                                                                            ),
                                                                            IdentifierName(
                                                                                "DuplicateValue"
                                                                            )
                                                                        ),
                                                                        IdentifierName(
                                                                            "duplicateValue"
                                                                        )
                                                                    )
                                                                )
                                                                /*,
                                                                ExpressionStatement(
                                                                    AssignmentExpression(
                                                                        SyntaxKind.SimpleAssignmentExpression,
                                                                        MemberAccessExpression(
                                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                                            ParseTypeName(
                                                                                $"Unity.Netcode.UserNetworkVariableSerialization<{contextTargetNode.Identifier.Text}>"
                                                                            ),
                                                                            IdentifierName(
                                                                                "DuplicateValue"
                                                                            )
                                                                        ),
                                                                        ParenthesizedLambdaExpression(
                                                                            ParameterList(
                                                                                SeparatedList(
                                                                                    new[] {
                                                                                        Parameter(
                                                                                                Identifier(
                                                                                                    "value"
                                                                                                )
                                                                                            )
                                                                                            .WithType(
                                                                                                IdentifierName(
                                                                                                    contextTargetNode.Identifier.Text
                                                                                                )
                                                                                            )
                                                                                            .WithModifiers(
                                                                                                TokenList(
                                                                                                    Token(
                                                                                                        SyntaxKind.InKeyword
                                                                                                    )
                                                                                                )
                                                                                            ),
                                                                                        Parameter(
                                                                                                Identifier(
                                                                                                    "duplicatedValue"
                                                                                                )
                                                                                            )
                                                                                            .WithType(
                                                                                                IdentifierName(
                                                                                                    contextTargetNode.Identifier.Text
                                                                                                )
                                                                                            )
                                                                                            .WithModifiers(
                                                                                                TokenList(
                                                                                                    Token(
                                                                                                        SyntaxKind.RefKeyword
                                                                                                    )
                                                                                                )
                                                                                            )
                                                                                    }
                                                                                )
                                                                            ),
                                                                            AssignmentExpression(
                                                                                SyntaxKind.SimpleAssignmentExpression,
                                                                                IdentifierName(
                                                                                    "duplicatedValue"
                                                                                ),
                                                                                IdentifierName(
                                                                                    "value"
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )*/
                                                            )
                                                        )
                                                )
                                        )
                                )
                        )
                        .NormalizeWhitespace()
                        .ToFullString(),
                    Encoding.UTF8
                )
            );
        }
    }
}